POST http://localhost:9000/auth/register
Content-Type: application/json

{
  "name": "wiloelgato123",
  "email": "wilo@admin.com",
  "password": "passwd"
}

###

POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "email": "wilo@admin.com",
  "password": "passwd"
}

###

GET http://localhost:9000/auth/google
Content-Type: application/json

###

GET http://localhost:9000/auth/profile